# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: libGDX Wiki

logo: "https://libgdx.com/assets/brand/logo.svg"
masthead_title: " " # disable the written title in the header
description: The official libGDX Wiki!
github_username:  libgdx

baseurl: "/wiki"
repository: crykn/wiki

markdown: CommonMarkGhPages
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

external_links:
  selector: 'a' # selector: 'main a'
  ignored_selectors:
    - a[href*=libgdx] # temporary
  marker_html: "<span class='ico-ext'><i class='fas fa-external-link-alt'></i></span>"

include:
  - _wiki

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - "jekyll-github-metadata"

defaults:
  # _wiki
  - scope:
      path: "_wiki"
      type: pages
    values:
      layout: single
